// dev
@host = localhost
@port = 8443
@baseUri = https://{{host}}:{{port}}
@uri = {{baseUri}}/api
@contentType = application/json
// @apiKey = 5KmgFcy1X7bbcbtSuOtXEZXYslKyB0n3g3xRmCaaNsAwB9dhOpKuhZ04Mfr2OKGL

### ping
// @name ping

GET {{baseUri}}/ping HTTP/1.1
Content-Type: {{contentType}}

### getUsers
// @name getUsers

GET {{uri}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "condition": "users.email = 'mail@koakh.com'"
}

### createUser
// @name createUser

POST {{uri}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "koakh",
  "email": "mail@koakh.com",
  "first_name": "Mario", 
  "last_name": "Monteiro"
}

### getUser
// @name getUser

GET {{uri}}/users/koakh HTTP/1.1
Content-Type: {{contentType}}

### deleteUser
// @name deleteUser

DELETE {{uri}}/users/koakh HTTP/1.1
Content-Type: {{contentType}}

