// dev
@host = localhost
@port = 8443
@baseUri = https://{{host}}:{{port}}
@uri = {{baseUri}}/api
@contentType = application/json

### ping
// @name ping

GET {{baseUri}}/ping HTTP/1.1
Content-Type: {{contentType}}

### redirect
// @name redirect

GET {{baseUri}}/redirect HTTP/1.1
Content-Type: {{contentType}}

### getAllUsers
// @name getAllUsers

GET {{uri}}/users HTTP/1.1
Content-Type: {{contentType}}

{
}

### getFilteredUsers
// @name getFilteredUsers

GET {{uri}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "condition": "users.email = 'mail@koakh.com'"
}

### getUser
// @name getUser

GET {{uri}}/users/ferreal HTTP/1.1
Content-Type: {{contentType}}

### createUser
// @name createUser

POST {{uri}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "koakh28",
  "email": "mail@koakh.com",
  "first_name": "Mario", 
  "last_name": "Monteiro"
}

### updateUser
// @name updateUser

PUT {{uri}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "koakh",
  "email": "koah@koakh.com",
  "first_name": "Koakh", 
  "last_name": "Koakh"
}

### deleteUser
// @name deleteUser

DELETE {{uri}}/users/koakh HTTP/1.1
Content-Type: {{contentType}}
